name: 'SPOT Server Issue 생성'
description: 'SPOT Server 팀의 Issue를 생성합니다. '
labels: [order]
title: 'Issue Title을 작성하세요'
body:
  - type: input
    id: ticketNum
    attributes:
      label: '상위 작업 Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'SPOT-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 'Issue 내용(Description)'
      description: 'Issue에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: 'Issue에 대해서 자세히 설명해주세요'
      value: |
        - About Details
    validations:
      required: true
