name: CD with Gradle

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 최신 버전에서 script를 실행
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Set Sentry auth token
        run: |
          echo "export SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.PROPERTIES }}" > src/main/resources/application-prod.yml

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_REPO }}

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            # 새로운 서버를 먼저 가동 (예: Green 서버)
            ENV_COLOR=$(curl --silent --fail https://teamspot.site/spot/current-env || echo "none")

            if [[ "$ENV_COLOR" == "blue" || "$ENV_COLOR" == "none" ]]; then
              # 블루 서버가 실행 중이거나 아무 서버도 돌아가고 있지 않다면 그린 서버를 실행
              sudo docker-compose -f docker-compose.yml up -d web-green
              sleep 20
              # 그린 서버가 정상적으로 작동하는지 확인 (예: HTTP 상태 코드 200 확인)
              if curl --silent --fail http://localhost:8081; then
                echo "Green server is working correctly."
                # 기존 서버 종료
                sudo docker-compose -f docker-compose.yml down web-blue
                # Nginx를 Green 서버로 전환
                sudo sed -i 's/8080/8081/' /etc/nginx/nginx.conf
                sudo systemctl restart nginx
              else
                echo "Green server is not responding correctly. Exiting."
                exit 1
              fi
            elif [[ "$ENV_COLOR" == "green" ]]; then
              # 그린 서버가 실행 중이면 블루 서버를 실행
              sudo docker-compose -f docker-compose.yml up -d web-blue
              sleep 20
              # 블루 서버가 정상적으로 작동하는지 확인
              if curl --silent --fail http://localhost:8080; then
                echo "Blue server is working correctly."
                # 기존 서버 종료
                sudo docker-compose -f docker-compose.yml down web-green
                # Nginx를 Blue 서버로 전환
                sudo sed -i 's/8081/8080/' /etc/nginx/nginx.conf
                sudo systemctl restart nginx
              else
                echo "Blue server is not responding correctly. Exiting."
                exit 1
              fi
            else
              echo "Unable to determine current environment, exiting."
              exit 1
            fi
