name: Testing

on:
  pull_request:
    branches:
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.TEST_PROPERTIES }}" > src/main/resources/application.yml

      - name: Run tests
        run: |
          ./gradlew test
