name: Testing

on:
  pull_request:
    branches:
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Upgrade Gradle to 8.8
        run: |
          ./gradlew wrapper --gradle-version <latest_version>

      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.PROPERTIES }}" > src/main/resources/application.yml

      - name: Run tests
        run: |
          ./gradlew test
